::letter <- function(){
	if(!getcon("lshift", "hold")){
		if(getcon("a", "press")) return "a"
		if(getcon("b", "press")) return "b"
		if(getcon("c", "press")) return "c"
		if(getcon("d", "press")) return "d"
		if(getcon("e", "press")) return "e"
		if(getcon("f", "press")) return "f"
		if(getcon("g", "press")) return "g"
		if(getcon("h", "press")) return "h"
		if(getcon("i", "press")) return "i"
		if(getcon("j", "press")) return "j"
		if(getcon("k", "press")) return "k"
		if(getcon("l", "press")) return "l"
		if(getcon("m", "press")) return "m"
		if(getcon("n", "press")) return "n"
		if(getcon("o", "press")) return "o"
		if(getcon("p", "press")) return "p"
		if(getcon("q", "press")) return "q"
		if(getcon("r", "press")) return "r"
		if(getcon("s", "press")) return "s"
		if(getcon("t", "press")) return "t"
		if(getcon("u", "press")) return "u"
		if(getcon("v", "press")) return "v"
		if(getcon("w", "press")) return "w"
		if(getcon("x", "press")) return "x"
		if(getcon("y", "press")) return "y"
		if(getcon("z", "press")) return "z"
		if(getcon("1", "press")) return "1"
		if(getcon("2", "press")) return "2"
		if(getcon("3", "press")) return "3"
		if(getcon("4", "press")) return "4"
		if(getcon("5", "press")) return "5"
		if(getcon("6", "press")) return "6"
		if(getcon("7", "press")) return "7"
		if(getcon("8", "press")) return "8"
		if(getcon("9", "press")) return "9"
		if(getcon("0", "press")) return "0"
	}
	if(getcon("lshift", "hold")){
		if(getcon("1", "press")) return "!"
		if(getcon("a", "press")) return "A"
		if(getcon("b", "press")) return "B"
		if(getcon("c", "press")) return "C"
		if(getcon("d", "press")) return "D"
		if(getcon("e", "press")) return "E"
		if(getcon("f", "press")) return "F"
		if(getcon("g", "press")) return "G"
		if(getcon("h", "press")) return "H"
		if(getcon("i", "press")) return "I"
		if(getcon("j", "press")) return "J"
		if(getcon("k", "press")) return "K"
		if(getcon("l", "press")) return "L"
		if(getcon("m", "press")) return "M"
		if(getcon("n", "press")) return "N"
		if(getcon("o", "press")) return "O"
		if(getcon("p", "press")) return "P"
		if(getcon("q", "press")) return "Q"
		if(getcon("r", "press")) return "R"
		if(getcon("s", "press")) return "S"
		if(getcon("t", "press")) return "T"
		if(getcon("u", "press")) return "U"
		if(getcon("v", "press")) return "V"
		if(getcon("w", "press")) return "W"
		if(getcon("x", "press")) return "X"
		if(getcon("y", "press")) return "Y"
		if(getcon("z", "press")) return "Z"
	}
	if(getcon("space", "press")) return " "
	if(getcon("comma", "press")) return ","
	if(getcon("period", "press")) return "."
	if(getcon("enter", "press")) return "\n"
	return ""
}